---
lint: |
  yamllint .
  ansible-lint .
dependency:
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
